name: go
on:
  workflow_call:
jobs:
  call-gotestbuildvettidy:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/gotestbuildvettidy.yml
  call-gosec:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/gosec.yml
  call-golangci-lint:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/golangci-lint.yml
