name: golangci-lint
on:
  push:
  pull_request:
  workflow_call:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.6
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint@latest
      - name: Run linter
        run: PATH=$PATH:~/go/bin golangci-lint run --out-format=github-actions -v -E gofmt
