name: golangci-lint
on:
  push:
  pull_request:
  workflow_call:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
          args: -v -E gofmt
          only-new-issues: true
