name: gotestbuildvettidy
on:
  push:
  pull_request:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.6

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...
    
    - name: Vet
      run: go vet -v ./...
      
    - name: Go Mod Tidy
      run: go mod tidy && git diff --exit-code -- go.mod go.sum
